title: Moisés Suíte
description: "Conjunto de ferramentas baseadas na aparição do Épico Moises no Topa Tudo por Dinheiro"
baseurl: "/moises-suite"
url: "http://flaviosilveira.com/"
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  # style: compressed
