title: Moisés Generator
description: "Gerador de texto baseado no diálogo do Épico Moises e Sílvio Santos"
baseurl: "/moises-generator"
url: "http://flaviosilveira.com/"
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
